import { useCallback, useEffect, useState } from "react";
import { api } from "../api/client.js";
import type { Penalty } from "../api/client.js";
import { exportRowsAsCsv } from "../utils/csv.js";
import { useToast } from "../components/Toast.js";
import { Icon } from "../components/Icon.js";
import { Provenance } from "../components/Provenance.js";

export function EnforcementPage() {
  const [penalties, setPenalties] = useState<Penalty[]>([]);
  const [loading, setLoading] = useState(true);
  const toast = useToast();

  const load = useCallback(() => {
    api.penalties()
      .then(setPenalties)
      .catch((e: unknown) => toast.error(e instanceof Error ? e.message : "Failed to load penalties"))
      .finally(() => setLoading(false));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    load();
    const iv = setInterval(load, 10_000);
    return () => clearInterval(iv);
  }, [load]);

  if (loading) return <div className="page"><div className="loading-state"><div className="spinner" />Loading…</div></div>;

  const totalFines = penalties.reduce((s, p) => s + (p.fine_amount ?? 0), 0);
  const highestSpeed = penalties.reduce((m, p) => Math.max(m, p.speed_kmh ?? 0), 0);

  const handleExport = () => {
    if (penalties.length === 0) { toast.info("No penalties to export"); return; }
    exportRowsAsCsv(`penalties-${new Date().toISOString().slice(0, 10)}.csv`, penalties);
    toast.success(`Exported ${penalties.length} penalty record(s) to CSV`);
  };

  return (
    <div className="page fade-in">
      <div className="page-header" style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: 12 }}>
        <div>
          <h1 className="page-title"><Icon name="gavel" size={22} /> Enforcement</h1>
          <p className="page-desc">Automated enforcement tickets generated by the AlertService for speed violations</p>
          <div style={{ marginTop: 6 }}>
            <Provenance rows={penalties} timestampOf={p => p.issued_at} label="penalty" />
          </div>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button className="btn btn-sm" onClick={load}><Icon name="refresh" size={14} /> Refresh</button>
          <button className="btn btn-sm" onClick={handleExport}><Icon name="download" size={14} /> Export CSV</button>
        </div>
      </div>

      <div className="kpi-strip" style={{ gridTemplateColumns: "repeat(4, 1fr)" }}>
        <div className="kpi-card"><div className="kpi-label">Total Tickets</div><div className="kpi-value text-cyan">{penalties.length}</div></div>
        <div className="kpi-card"><div className="kpi-label">Total Fines</div><div className="kpi-value text-green">PKR {totalFines.toLocaleString()}</div></div>
        <div className="kpi-card"><div className="kpi-label">Highest Speed</div><div className="kpi-value text-red">{highestSpeed} km/h</div></div>
        <div className="kpi-card"><div className="kpi-label">Duplicate Protection</div><div className="kpi-value text-purple">Active</div><div className="kpi-sub">Idempotent receiver</div></div>
      </div>

      <div className="table-wrap">
        <table>
          <thead><tr><th>Plate</th><th>Speed</th><th>Limit</th><th>Excess</th><th>Fine</th><th>Status</th><th>Camera</th><th>Event ID</th></tr></thead>
          <tbody>
            {penalties.length === 0 ? (
              <tr><td colSpan={8}>
                <div className="empty-state-rich">
                  <Icon name="gavel" size={32} />
                  <div className="empty-title">No penalties issued yet</div>
                  <div className="empty-sub">Publish a Speed Violation from the Event Simulator to see one. The AlertService will issue a penalty based on the active FinePolicy and the violation will appear here.</div>
                </div>
              </td></tr>
            ) : penalties.map(p => {
              const excess = (p.speed_kmh ?? 0) - (p.speed_limit_kmh ?? 0);
              return (
                <tr key={p.id}>
                  <td><span className="plate">{p.vehicle_plate ?? "—"}</span></td>
                  <td className="mono fw-600 text-red">{p.speed_kmh ?? 0} km/h</td>
                  <td className="mono">{p.speed_limit_kmh ?? 0} km/h</td>
                  <td><span className={`badge ${excess > 25 ? "badge-red" : excess > 10 ? "badge-amber" : "badge-cyan"}`}>+{excess} km/h</span></td>
                  <td className="fw-600 text-green">PKR {(p.fine_amount ?? 0).toLocaleString()}</td>
                  <td><span className="badge badge-green">{p.status ?? "ISSUED"}</span></td>
                  <td className="mono text-muted" style={{ fontSize: 11 }}>{(p.camera_id ?? "—").substring(0, 8)}</td>
                  <td className="mono text-muted" style={{ fontSize: 10 }}>{(p.event_id ?? "—").substring(0, 12)}…</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
